### ISSUE TITLE
Pieces OS apparently stuck - VS extension not working

### ISSUE THREAD

**Issue by Andrea3i** [pieces-app/support#474]
### Software

Pieces OS, Visual Studio

### Operating System / Platform

Windows

### Your Pieces OS Version

10.1.14.0

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

Hi, I have just installed Pieces on my Windows 11 laptop and I'm experiencing some problems, specifically with Pieces OS and the Visual Studio extension.
Somehow, the desktop app works fine.

Pieces OS seems stuck in the system tray. Every time I click it, a "Sentry Error Event" appears in the log file and the application doesn't do anything.
At the same time, the Visual Studio extension shows a window saying that Pieces OS is not running. If I click on the launch button, a "route not found" message appears for a moment and then the "Pieces OS is not running" message comes back.

I checked for updates on the Pieces Suite app, but there are no update.

I'm attaching the log file and the response of the http://localhost:1000/applications url. I tried navigating manually to the url opened by the launch button in Visual Studio [(url)](http://localhost:1000/?application=%7B%22name%22%3A%22VISUAL_STUDIO%22%2C%22platform%22%3A%22WINDOWS%22%2C%22privacy%22%3A%22OPEN%22%2C%22capabilities%22%3A%22BLENDED%22%2C%22mechanism%22%3A%22MANUAL%22%2C%22schema%22%3A%7B%22semantic%22%3A%22MAJOR_0_MINOR_0_PATCH_1%22%2C%22migration%22%3A0%7D%2C%22id%22%3A%229ab3c1de-0625-408e-8d42-8e2c48e11d0c%22%2C%22version%22%3A%223.0.0%22%2C%22onboarded%22%3Afalse%2C%22automaticUnload%22%3Afalse%7D&capabilities=1048575&theme=%7B%22darkMode%22%3Atrue%2C%22scaffoldBackgroundColor%22%3A-14737633%2C%22primary%22%3A-328966%2C%22secondary%22%3A-14737633%2C%22onPrimary%22%3A-10724260%2C%22onSecondary%22%3A-328966%2C%22primaryContainer%22%3A-13421773%2C%22surface%22%3A-13750738%2C%22onSurface%22%3A-328966%2C%22error%22%3A-934979%2C%22onError%22%3A-1%7D) and the response is "Route not found".

Thank you in advance.

[log-11252024.txt](https://github.com/user-attachments/files/17903747/log-11252024.txt)
[applications.txt](https://github.com/user-attachments/files/17903752/applications.txt)

**Comment by sam-at-pieces** [comment]
Thank you for raising this @Andrea3i, it must be frustrating! @sam-p-at-pieces here is the [sentry issue](https://pieces.sentry.io/issues/6082482383/events/b12bca0b6e3f4b3b8ff76a8cff9dcabd/?project=5937482&referrer=issue-list&statsPeriod=14d). It looks like the OS server toolbar is not launching correctly.

**Comment by sam-p-at-pieces** [comment]
@robert-at-pieces You may have more insight here. Any ideas why the toolbar might be failing when trying to launch the Visual Studio plugin?

**Comment by robert-at-pieces** [comment]
@Andrea3i an update on this: There seems to be an issue with version 3.0.0 of the Visual Studio plugin during initialization of our new 'Saved Materials' webview based Tool Window. This issue has been upgraded to a P0 for the Visual Studio plugin and I will be looking to get a hotfix out as soon as possible.

Thank you for bringing this to our attention.

**Comment by robert-at-pieces** [comment]
@Andrea3i -- We have released Visual Studio plugin version 3.0.1 to resolve a UI thread hang.

We will also be releasing Pieces OS version 10.1.15 shortly. This version includes a change to how ports are chosen to serve webviews for our tool window integrations.

If together these versions do not resolve your issue, please reach out. I will gladly schedule a time to gather a screen recording of the issue if you are willing.

**Comment by Andrea3i** [comment]
Thank you for the update.
I updated both the VS extension and Pieces OS but it's not working. When I click the icon in the system tray, nothing happens. Also, now it seems that Pieces OS restarts on its own sometimes, as I see the notifications saying that it's running in background a couple of times after launching it.
I'm attaching the new log file.

[log-11262024.txt](https://github.com/user-attachments/files/17915250/log-11262024.txt)

**Comment by mark-at-pieces** [comment]
Hey @Andrea3i I can see you are having trouble with the applets, and the tentative solution we pushed did not resolve your issues,

Would you mind finding sometime on my calendar to further debug?

here is a [link](https://calendar.app.google/NSLnPyE8uxTAjuGg7)
