### ISSUE TITLE
Models Download Fail

### ISSUE THREAD

**Issue by surya-sengupta** [pieces-app/support#608]
### Software

Desktop Application

### Operating System / Platform

Windows

### Your Pieces OS Version

11.0.4

### Early Access Program

- [ ] Yes, this is related to an Early Access Program feature.

### Kindly describe the bug and include as much detail as possible on what you were doing so we can reproduce the bug.

I'm not able to download any of the models for ollama.
[log-02022025.txt](https://github.com/user-attachments/files/18631166/log-02022025.txt)

**Comment by brian-at-pieces** [comment]
@surya-sengupta sorry you're having this issue. We just released Pieces OS version 11.1.0 which includes some stability upgrades for Ollama. Would you mind updating and then retrying the download? Thanks

**Comment by surya-sengupta** [comment]
Now it's fixed. Thanks

**Comment by surya-sengupta** [comment]
Nope, still having the same issue. This stopped working after one day. I did a clean reinstall but didn't worked.

[log-02102025.txt](https://github.com/user-attachments/files/18732103/log-02102025.txt)
